name: Org Crud Tests and Linter

on:
  push:
  pull_request:

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: temurin
          java-version: 18
          cache: 'maven'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@05cb4bfdf57855f122e75b71e45224775cdfc4a0
        with:
          tools-deps: latest
      - name: Cache dependencies
        uses: actions/cache@v3.0.8
        env:
          cache-name: cache-clj
        with:
          path: ~/.m2
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Run Tests
        run: clojure -M:test

  Linter:
    runs-on: ubuntu-latest
    steps:
    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2022.09.08'

    - uses: actions/checkout@v3.0.2

    - name: Lint
      run: clj-kondo --lint src:test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
