name: Org Crud Tests and Linter

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: latest
          bb: latest

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-clj
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Run Tests (JVM)
        run: clojure -M:test

      - name: Run Tests (Babashka)
        run: ./bb_test_runner.clj

  Linter:
    runs-on: ubuntu-latest
    steps:
    - name: Setup clj-kondo
      uses: DeLaGuardo/setup-clj-kondo@master
      with:
        version: '2023.07.13'

    - uses: actions/checkout@v3

    - name: Lint
      run: clj-kondo --lint src:test --config '{:output {:pattern "::{{level}} file={{filename}},line={{row}},col={{col}}::{{message}}"}}'
